server:
  port: 3499
spring:
  main:
    web-application-type: servlet
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}/riguru?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
bakamc:
  text:
    playerInfoHover:
      - "玩家名称 : %name%\n"
      - "玩家显示名 : %displayName%\n"
      - "UUID : %uuid%\n"
      - "所在小镇 : %town%\n"
      - "玩家等级 : %level%\n"
      - "玩家总经验 : %experience%\n"
      - "生命值 : %health%/%maxHealth%\n"
      - "所在维度 : %dimension%\n"
      - "点击私聊"
    playerInfoClickCommand: "/bakamc:chat msg %name% "
    townHover:
      - "小镇ID : %id%\n"
      - "小组名称 : %name%\n"
      - "小镇简称 : %shortName%\n"
      - "创建时间 : %createTime%\n"
      - "镇长 : %mayor%\n"
      - "管理员 : %admin%\n"
      - "成员 : %member%\n"
      - "点击申请加入该小镇"
    townClickCommand: "/bakamc:town application %id%"
    serverInfoClickCommand: "/server %serverID%"
  chat:
    chatFormat: "#{§6[§rserverName§6]}#{§6[§rtownShortName§6]}#{§6[§r§bplayerName§6]}§b:§r #{message}"
    whisperSenderFormat: "§7你悄悄对#{§6[§r§7receiver§6]}§7说§b:§r #{message}"
    whisperReceiverFormat: "#{§6[§rserverName§6]}#{§6[§rtown§6]}#{§6[§r§bplayerName§6]}§7悄悄对你说§b:§r #{message}"
    atFormat: "§b%at%§r"
    #只会替换原始消息文本
    messageMapping:
      "[&0]": "§0"
      "[&1]": "§1"
      "[&2]": "§2"
      "[&3]": "§3"
      "[&4]": "§4"
      "[&5]": "§5"
      "[&6]": "§6"
      "[&7]": "§7"
      "[&8]": "§8"
      "[&9]": "§9"
      "[&a]": "§a"
      "[&b]": "§b"
      "[&c]": "§c"
      "[&d]": "§d"
      "[&e]": "§e"
      "[&f]": "§f"
      "[&g]": "§g"
      "[&h]": "§h"
      "[&u]": "§u"
      "[&l]": "§l"
      "[&o]": "§o"
      "[&m]": "§m"
      "[&k]": "§k"
      "[&r]": "§r"