name: BakaMC
version: '${projectVersion}'
main: cn.bakamc.folia.BakaMC
bootstrapper: cn.bakamc.folia.BakaMCBootstrap
loader: cn.bakamc.folia.BakaMCLoader
api-version: '1.21'
author: forpleuvoir

folia-supported: true

description: ${description}

load: POSTWORLD

#dependencies:
#  server:
